tutorial:
  client:
    duration: 10000

spring:
  rabbitmq:
    virtual-host: /
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1
        prefetch: 1
    # template:
    #   reply-timeout: 60000