spring:
  application:
    name: rabbitmq-chat
  rabbitmq:
    username: admin
    password: Asdf1234$
    virtual-host: chat

rabbitmq:
  server:
    chat-concurrent: 10
  
logging:
  level:
    org: ERROR